#!/bin/bash
#
# Copyright (C) 2011 Eric Herman
# license: http://www.gnu.org/licenses/lgpl-2.1.html
#
# initially thrown together by Eric Herman on 2011 May 04
#
# much of this is simply automating Cross-Compiled Linux From Scratch
#  http://cross-lfs.org/
#   Copyright (C) 2005-2010 Joe Ciccone, Jim Gifford & Ryan Oliver
#   license: http://www.opencontent.org/openpub/
#
# CLFS is based upon Based on LFS, as well.
#  http://www.linuxfromscratch.org/lfs/
#   Copyright (C) 1999-2010 Gerard Beekmans
#   license: Attribution-NonCommercial-ShareAlike 2.0
#
# some inspiration was from DIY Linux
#  http://diy-linux.org/
#   Copyright (C) 2004-2008, 2009 Greg Schafer
#   license: http://www.gnu.org/licenses/fdl.html
#

export SYSROOT="/lfs"

echo "setting the root password to match lfs" &&
export PASSWD=$(cat /etc/shadow | grep "^lfs" | cut --delimiter=':' -f2) &&
cp -v ${SYSROOT}/etc/passwd{,.orig} &&
sed -e "s@:x:@:$PASSWD:@" ${SYSROOT}/etc/passwd.orig > ${SYSROOT}/etc/passwd &&

mknod -m 600 ${SYSROOT}/dev/console c 5 1 &&
mknod -m 666 ${SYSROOT}/dev/null c 1 3 &&
mknod -m 600 ${SYSROOT}/lib/udev/devices/console c 5 1 &&
mknod -m 666 ${SYSROOT}/lib/udev/devices/null c 1 3 &&

chown -Rv 0:0 ${SYSROOT} &&
echo "The following files are to be owned by the group utmp not by root." &&
chgrp -v 13 ${SYSROOT}/var/run/utmp ${SYSROOT}/var/log/lastlog &&
echo "YAY" || exit $?

echo "WOOT"

