#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr &&
  echo '#define YYENABLE_NLS 1' >> config.h
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
