#!/bin/bash

function configure_commands()
{
 echo "no configure"
}

function make_commands()
{
 echo "no make"
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install-bootscripts &&
  make install-network &&
  make install-service-dhcpcd &&
  echo "INSTALL COMPLETE"
}
