#!/bin/bash

function configure_commands()
{
 echo "no configure"
}

function make_commands()
{
 echo "no make"
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make install-bootscripts &&
  make install-network &&
  make install-service-dhcpcd &&
  pushd /etc/sysconfig/network-devices/services &&
  ln -sv /sbin/dhcpcd &&
  popd &&
  make install-sshd &&
  echo "INSTALL COMPLETE"
}
