#!/bin/bash

export BUILD_DIR=../build-eglibc

function configure_commands()
{
  cp -iv ../eglibc-2.13/scripts/test-installation.pl{,.orig} &&
  sed -i \
    's/\(&& $name ne\) "db1"/ & \1 "nss_test1"/' \
    ../eglibc-2.13/scripts/test-installation.pl &&
  LINKER=$(readelf -l /tools/bin/bash | sed -n \
    's@.*interpret.*/tools\(.*\)]$@\1@p') &&
  sed -i \
    "s|libs -o|libs -L/usr/lib -Wl,-dynamic-linker=${LINKER} -o|" \
    ../eglibc-2.13/scripts/test-installation.pl &&
  unset LINKER &&
  echo "slibdir=/lib" >> configparms &&
  CFLAGS="-mtune=generic -g -O2" \
    ../eglibc-2.13/configure \
    --prefix=/usr \
    --disable-profile \
    --enable-add-ons \
    --enable-kernel=2.6.35 \
    --libexecdir=/usr/lib/eglibc \
    --libdir=/usr/lib
}

function make_commands()
{
  make
}

function test_commands()
{
  cp -v ../eglibc-2.13/iconvdata/gconf-modules iconvdata
  make -k check 2>&1 | tee eglibc-check-log
  grep Error eglibc-check-log
  echo "whatever"
}

function install_commands()
{
  touch /etc/ld.so.conf &&
  ln -sv ld-2.13.so /lib/ld-linux.so.2 &&
  make install &&
  rm -v /lib/ld-linux.so.2 &&
  cp -v /usr/bin/ldd{,.bak} &&
  sed '/RTLDLIST/s%/ld-linux.so.2 /lib64%%' /usr/bin/ldd.bak > /usr/bin/ldd &&
  rm -v /usr/bin/ldd.bak &&
  make localedata/install-locales &&
  echo "checkpoint 1" || return $?;
  cat > /etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

hosts: files dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF
  cp -v --remove-destination /usr/share/zoneinfo/Europe/Amsterdam \
    /etc/localtime &&
echo "checkpoint 2" || return $?;
cat > /etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf

/usr/local/lib
/opt/lib

# End /etc/ld.so.conf
EOF
  echo "INSTALL COMPLETE"
}
