#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  ln -sv libfl.a /usr/lib/libl.a &&
  cat > /usr/bin/lex << "EOF"
#!/bin/sh
# Begin /usr/bin/lex

exec /usr/bin/flex -l "$@"

# End /usr/bin/lex
EOF
  chmod -v 755 /usr/bin/lex &&
  echo "INSTALL COMPLETE"
}
