#!/bin/bash
function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make -k check || echo "DARN $? Oh, well."
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
