#!/bin/bash
function configure_commands()
{
  CPPFLAGS=-fexceptions CC="gcc -isystem /usr/include" \
  CXX="g++ -isystem /usr/include" \
  LDFLAGS="-Wl,-rpath-link,/usr/lib:/lib" \
    ./configure --prefix=/usr --enable-cxx --enable-mpbsd
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
