#!/bin/bash

function configure_commands()
{
  sed -i 's@-is@&R@g' configure &&
  sed -i 's@MANPATH./usr/man@#&@g' src/man.conf.in &&
  sed -i 's@MANPATH./usr/local/man@#&@g' src/man.conf.in &&
  ./configure \
    -confdir=/etc
}

function make_commands()
{
  make
}

function test_commands()
{
  echo "no tests"
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
