#!/bin/bash

function configure_commands()
{
  ./config \
    --prefix=/usr \
    --openssldir=/etc/ssl \
    shared
}

function make_commands()
{
  make MANDIR=/usr/share/man
}

function test_commands()
{
  echo "no make check"
}

function install_commands()
{
  make MANDIR=/usr/share/man install &&
  ln -sv ../../etc/ssl /usr/share &&
  cp -v -r certs /etc/ssl &&
  install -m755 -d -v /usr/share/doc/openssl-1.0.0c &&
  cp -v -r doc/{HOWTO,README,*.{txt,html,gif}} \
    /usr/share/doc/openssl-1.0.0c &&
  echo "INSTALL COMPLETE"
}
