#!/bin/bash

function configure_commands()
{
  sed -i -e '/^BUILD_ZLIB/s/True/False/' \
         -e '/^INCLUDE/s,\./zlib-src,/usr/include,' \
         -e '/^LIB/s,\./zlib-src,/usr/lib,' \
         cpan/Compress-Raw-Zlib/config.in &&
  ./configure.gnu \
    --prefix=/usr \
    -Dvenorprefix=/usr \
    -Dman1dir=/usr/share/man/man1 \
    -Dman3dir=/usr/share/man/man3 \
    -Dpager="/bin/less -isR" \
    -Dusethreads \
    -Duseshrplib
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  echo "INSTALL COMPLETE"
}
