#!/bin/bash

function configure_commands()
{
  echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h &&
  ./configure \
    --prefix=/usr \
    --enable-multibyte
}

function make_commands()
{
  make
}

function test_commands()
{
  make test
}

function install_commands()
{
  make install &&
  ln -sv vim /usr/bin/vi &&
  echo "INSTALL COMPLETE"
}
