#!/bin/bash

function configure_commands()
{
  ./configure \
    --prefix=/usr
}

function make_commands()
{
  make
}

function test_commands()
{
  make check
}

function install_commands()
{
  make install &&
  mv -v /usr/bin/{xz,lzma,lzcat,unlzma,unxz,xzcat} /bin &&
  echo "INSTALL COMPLETE"
}
