#!/bin/bash
#
chown util-linux:util-linux /bin/dmesg
chown util-linux:util-linux /bin/lsblk
chown util-linux:util-linux /bin/findmnt
chown util-linux:util-linux /bin/more
chown util-linux:util-linux /bin/mount
chown util-linux:util-linux /bin/umount
#
chown util-linux:util-linux /sbin/agetty
chown util-linux:util-linux /sbin/blkid
chown util-linux:util-linux /sbin/blockdev
chown util-linux:util-linux /sbin/cfdisk
chown util-linux:util-linux /sbin/ctrlaltdel
chown util-linux:util-linux /sbin/fdisk
chown util-linux:util-linux /sbin/findfs
chown util-linux:util-linux /sbin/fsck
chown util-linux:util-linux /sbin/fsck.cramfs
chown util-linux:util-linux /sbin/fsck.minix
chown util-linux:util-linux /sbin/fstrim
chown util-linux:util-linux /sbin/hwclock
chown util-linux:util-linux /sbin/losetup
chown util-linux:util-linux /sbin/mkfs
chown util-linux:util-linux /sbin/mkfs.bfs
chown util-linux:util-linux /sbin/mkfs.cramfs
chown util-linux:util-linux /sbin/mkfs.minix
chown util-linux:util-linux /sbin/mkswap
chown util-linux:util-linux /sbin/pivot_root
chown util-linux:util-linux /sbin/sfdisk
chown util-linux:util-linux /sbin/swaplabel
chown -h util-linux:util-linux /sbin/swapoff
chown util-linux:util-linux /sbin/swapon
chown util-linux:util-linux /sbin/switch_root
chown util-linux:util-linux /sbin/wipefs
chown util-linux:util-linux /sbin/fsfreeze
#
chown util-linux:util-linux /usr/bin/cal
chown util-linux:util-linux /usr/bin/chkdupexe
chown util-linux:util-linux /usr/bin/chrt
chown util-linux:util-linux /usr/bin/col
chown util-linux:util-linux /usr/bin/colcrt
chown util-linux:util-linux /usr/bin/colrm
chown util-linux:util-linux /usr/bin/column
chown util-linux:util-linux /usr/bin/cytune
chown util-linux:util-linux /usr/bin/ddate
chown util-linux:util-linux /usr/bin/fallocate
chown util-linux:util-linux /usr/bin/flock
chown util-linux:util-linux /usr/bin/getopt
chown util-linux:util-linux /usr/bin/hexdump
chown util-linux:util-linux /usr/bin/ionice
chown util-linux:util-linux /usr/bin/ipcmk
chown util-linux:util-linux /usr/bin/ipcrm
chown util-linux:util-linux /usr/bin/ipcs
chown util-linux:util-linux /usr/bin/isosize
chown util-linux:util-linux /usr/bin/line
chown util-linux:util-linux /usr/bin/logger
chown util-linux:util-linux /usr/bin/look
chown util-linux:util-linux /usr/bin/lscpu
chown util-linux:util-linux /usr/bin/mcookie
chown util-linux:util-linux /usr/bin/namei
chown util-linux:util-linux /usr/bin/pg
chown util-linux:util-linux /usr/bin/rename
chown util-linux:util-linux /usr/bin/renice
chown util-linux:util-linux /usr/bin/rev
chown util-linux:util-linux /usr/bin/script
chown util-linux:util-linux /usr/bin/scriptreplay
chown util-linux:util-linux /usr/bin/setarch
chown util-linux:util-linux /usr/bin/setsid
chown util-linux:util-linux /usr/bin/setterm
chown util-linux:util-linux /usr/bin/tailf
chown util-linux:util-linux /usr/bin/taskset
chown util-linux:util-linux /usr/bin/ul
chown util-linux:util-linux /usr/bin/unshare
chown util-linux:util-linux /usr/bin/uuidgen
chown util-linux:util-linux /usr/bin/whereis
chown -h util-linux:util-linux /usr/bin/linux32
chown -h util-linux:util-linux /usr/bin/linux64
chown -h util-linux:util-linux /usr/bin/i386
chown -h util-linux:util-linux /usr/bin/x86_64
#
chown util-linux:util-linux /usr/sbin/addpart
chown util-linux:util-linux /usr/sbin/delpart
chown util-linux:util-linux /usr/sbin/fdformat
chown util-linux:util-linux /usr/sbin/ldattach
chown util-linux:util-linux /usr/sbin/readprofile
chown util-linux:util-linux /usr/sbin/rtcwake
chown util-linux:util-linux /usr/sbin/tunelp
chown util-linux:util-linux /usr/sbin/uuidd
#
chown util-linux:util-linux /usr/lib/libuuid.a
chown -h util-linux:util-linux /usr/lib/libuuid.so
chown util-linux:util-linux /lib/libuuid.so.1.3.0
chown -h util-linux:util-linux /lib/libuuid.so.1
#
chown -h util-linux:util-linux /usr/lib/libblkid.so
chown util-linux:util-linux /usr/lib/libblkid.a
chown util-linux:util-linux /lib/libblkid.so.1.1.0
chown -h util-linux:util-linux /lib/libblkid.so.1
#
chown util-linux:util-linux /usr/share/man/man3/libblkid.3
chown util-linux:util-linux /usr/share/man/man3/*uuid*
#
chown util-linux:util-linux /usr/share/man/man8/addpart.8
chown util-linux:util-linux /usr/share/man/man8/agetty.8
chown util-linux:util-linux /usr/share/man/man8/blkid.8
chown util-linux:util-linux /usr/share/man/man8/isosize.8
chown util-linux:util-linux /usr/share/man/man8/mkfs.8
chown util-linux:util-linux /usr/share/man/man8/mkswap.8
chown util-linux:util-linux /usr/share/man/man8/fsck.minix.8
chown util-linux:util-linux /usr/share/man/man8/mkfs.minix.8
chown util-linux:util-linux /usr/share/man/man8/mkfs.bfs.8
chown util-linux:util-linux /usr/share/man/man8/fdformat.8
chown util-linux:util-linux /usr/share/man/man8/blockdev.8
chown util-linux:util-linux /usr/share/man/man8/swaplabel.8
chown util-linux:util-linux /usr/share/man/man8/setarch.8
chown util-linux:util-linux /usr/share/man/man1/cal.1
chown util-linux:util-linux /usr/share/man/man1/chkdupexe.1
chown util-linux:util-linux /usr/share/man/man1/chrt.1
chown util-linux:util-linux /usr/share/man/man1/column.1
chown util-linux:util-linux /usr/share/man/man1/col.1
chown util-linux:util-linux /usr/share/man/man1/colrm.1
chown util-linux:util-linux /usr/share/man/man1/colcrt.1
chown util-linux:util-linux /usr/share/man/man1/colcrt.1
chown util-linux:util-linux /usr/share/man/man1/colrm.1
chown util-linux:util-linux /usr/share/man/man1/column.1
chown util-linux:util-linux /usr/share/man/man8/cytune.8
chown util-linux:util-linux /usr/share/man/ru/man1/ddate.1
chown util-linux:util-linux /usr/share/man/man1/ddate.1
chown util-linux:util-linux /usr/share/man/man8/delpart.8
chown util-linux:util-linux /usr/share/man/man1/dmesg.1
chown util-linux:util-linux /usr/share/man/man1/flock.1
chown util-linux:util-linux /usr/share/man/man1/getopt.1
chown util-linux:util-linux /usr/share/man/man1/hexdump.1
chown util-linux:util-linux /usr/share/man/man1/ionice.1
chown util-linux:util-linux /usr/share/man/man1/ipcmk.1
chown util-linux:util-linux /usr/share/man/man1/ipcrm.1
chown util-linux:util-linux /usr/share/man/man1/ipcs.1
chown util-linux:util-linux /usr/share/man/man8/ldattach.8
chown util-linux:util-linux /usr/share/man/man1/line.1
chown util-linux:util-linux /usr/share/man/man1/logger.1
chown util-linux:util-linux /usr/share/man/man1/look.1
chown util-linux:util-linux /usr/share/man/man1/lscpu.1
chown util-linux:util-linux /usr/share/man/man1/mcookie.1
chown util-linux:util-linux /usr/share/man/man1/more.1
chown util-linux:util-linux /usr/share/man/man8/umount.8
chown util-linux:util-linux /usr/share/man/man8/mount.8
chown util-linux:util-linux /usr/share/man/man1/mountpoint.1
chown util-linux:util-linux /usr/share/man/man1/namei.1
chown util-linux:util-linux /usr/share/man/man1/pg.1
chown util-linux:util-linux /usr/share/man/man1/readprofile.1
chown util-linux:util-linux /usr/share/man/man1/rename.1
chown util-linux:util-linux /usr/share/man/man1/renice.1
chown util-linux:util-linux /usr/share/man/man1/rev.1
chown util-linux:util-linux /usr/share/man/man8/rtcwake.8
chown util-linux:util-linux /usr/share/man/man5/initscript.5
chown util-linux:util-linux /usr/share/man/man1/script.1
chown util-linux:util-linux /usr/share/man/man1/scriptreplay.1
chown util-linux:util-linux /usr/share/man/man1/scriptreplay.1
chown util-linux:util-linux /usr/share/man/man8/setarch.8
chown util-linux:util-linux /usr/share/man/man1/setsid.1
chown util-linux:util-linux /usr/share/man/man1/setterm.1
chown util-linux:util-linux /usr/share/man/man1/tailf.1
chown util-linux:util-linux /usr/share/man/man1/taskset.1
chown util-linux:util-linux /usr/share/man/man8/tunelp.8
chown util-linux:util-linux /usr/share/man/man8/umount.8
chown util-linux:util-linux /usr/share/man/man8/uuidd.8
chown util-linux:util-linux /usr/share/man/man1/uuidgen.1
chown util-linux:util-linux /usr/share/man/man1/whereis.1
chown util-linux:util-linux /usr/share/man/man1/fallocate.1
chown util-linux:util-linux /usr/share/man/man8/findfs.8
chown util-linux:util-linux /usr/share/man/man8/fdisk.8
chown util-linux:util-linux /usr/share/man/man8/sfdisk.8
chown util-linux:util-linux /usr/share/man/man8/cfdisk.8
chown util-linux:util-linux /usr/share/man/man8/wipefs.8
chown util-linux:util-linux /usr/share/man/man8/lsblk.8
chown util-linux:util-linux /usr/share/man/man8/findmnt.8
chown util-linux:util-linux /usr/share/man/man8/fsfreeze.8
chown util-linux:util-linux /usr/share/man/man8/fstrim.8
chown util-linux:util-linux /usr/share/man/man8/cytune.8
chown util-linux:util-linux /usr/share/man/man1/unshare.1
#
chown -R util-linux:install /usr/share/getopt
#
chown -R util-linux:install /usr/include/uuid
chown -R util-linux:install /usr/include/blkid
chown -R util-linux:install /usr/include/libmount
#
chown util-linux:util-linux /usr/lib/pkgconfig/uuid.pc
chown util-linux:util-linux /usr/lib/pkgconfig/blkid.pc
chown util-linux:util-linux /usr/lib/pkgconfig/mount.pc
#
chown -h util-linux:util-linux /lib/libmount*
#
for MO in $(find /usr/share/locale -name 'util-linux.mo'); do
    chown util-linux:util-linux ${MO}
done

chown util-linux:util-linux /usr/share/man/man8/ctrlaltdel.8
chown util-linux:util-linux /usr/share/man/man8/pivot_root.8
chown util-linux:util-linux /usr/share/man/man8/switch_root.8
chown util-linux:util-linux /usr/share/man/man8/linux32.8
chown util-linux:util-linux /usr/share/man/man8/linux64.8
chown util-linux:util-linux /usr/share/man/man8/i386.8
chown util-linux:util-linux /usr/share/man/man8/x86_64.8
chown util-linux:util-linux /usr/share/man/man1/ul.1
chown util-linux:util-linux /usr/share/man/man8/hwclock.8
chown util-linux:util-linux /usr/share/man/man8/swapoff.8
chown util-linux:util-linux /usr/share/man/man5/fstab.5
chown util-linux:util-linux /usr/share/man/man8/fstab-decode.8
chown util-linux:util-linux /usr/share/man/man8/swapon.8
chown util-linux:util-linux /usr/share/man/man8/losetup.8
chown util-linux:util-linux /usr/share/man/man8/fsck.8
